from docx import Document
from docx.shared import Pt
from pathlib import Path


REPORT_DIR = Path("generated_reports")
REPORT_DIR.mkdir(exist_ok=True)


def generate_inspection_report(filename, analysis):
    doc = Document()

    # Title
    title = doc.add_heading("INDUSTRIAL INSPECTION REPORT", level=0)
    title.alignment = 1

    doc.add_paragraph(f"Source Document: {filename}")
    doc.add_paragraph("Generated by: Sovereign AI Workbench")
    doc.add_paragraph("Processing Mode: Local / On-Premise AI")

    # Key Findings
    doc.add_heading("1. Key Findings", level=1)

    for finding in analysis.get("key_findings", []):
        doc.add_paragraph(finding, style="List Bullet")

    # Recommended Actions
    doc.add_heading("2. Recommended Actions", level=1)

    for action in analysis.get("recommended_actions", []):
        doc.add_paragraph(action, style="List Bullet")

    # Overall Assessment
    doc.add_heading("3. Overall Assessment", level=1)
    doc.add_paragraph(
        analysis.get(
            "overall_assessment",
            "No overall assessment available."
        )
    )

    # Approval section
    doc.add_heading("4. Approval", level=1)

    table = doc.add_table(rows=3, cols=2)
    table.style = "Table Grid"

    table.cell(0, 0).text = "Prepared By"
    table.cell(0, 1).text = "Sovereign AI Workbench"

    table.cell(1, 0).text = "Reviewed By"
    table.cell(1, 1).text = "________________________"

    table.cell(2, 0).text = "Approval Status"
    table.cell(2, 1).text = "Pending Review"

    # Footer
    section = doc.sections[0]
    footer = section.footer
    footer.paragraphs[0].text = (
        "Confidential - Local Processing - Demonstration Prototype"
    )

    # Basic font formatting
    for paragraph in doc.paragraphs:
        for run in paragraph.runs:
            run.font.name = "Arial"
            run.font.size = Pt(10)

    output_path = REPORT_DIR / "inspection_report.docx"
    doc.save(output_path)

    return str(output_path)
